server:
  port: 9296

spring:
  application:
    name: CloudConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aakarshit-agarwal/MyFitCouldConfigServer
          clone-on-start: true
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
