server:
  port: 9296

spring:
  application:
    name: CloudConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aakarshit-agarwal/MyFitCouldConfigServer
          clone-on-start: true
